
declare namespace JSX {
    interface IntrinsicAttributes { 
        "data-align-items"?: "start" | "self-start" | "end" | "self-end" | "center" | "stretch" | "normal" | "baseline",
        "data-background-color"?: "red" | "blue" | "green" | "lightgreen" | "lightyellow" | "gold" | "goldenrod" | "fuchsia" | "black" | "white" | "accent",
        "data-border"?: "none" | "frame",
        "data-border-style"?: "solid" | "dashed" | "dotted" | "double" | "groove" | "inset" | "none" | "outset" | "ridge",
        "data-border-width"?: "thin" | "thick" | "thinner" | "thicker" | "thinnest" | "thickest",
        "data-border-color"?: "accent",
        "data-border-radius"?: "full",
        "data-border-left-style"?: "solid" | "dashed" | "dotted" | "double" | "groove" | "inset" | "none" | "outset" | "ridge",
        "data-border-left-width"?: "thin" | "thick" | "thinner" | "thicker" | "thinnest" | "thickest",
        "data-border-left-color"?: "accent",
        "data-border-right-style"?: "solid" | "dashed" | "dotted" | "double" | "groove" | "inset" | "none" | "outset" | "ridge",
        "data-border-right-width"?: "thin" | "thick" | "thinner" | "thicker" | "thinnest" | "thickest",
        "data-border-right-color"?: "accent",
        "data-border-top-style"?: "solid" | "dashed" | "dotted" | "double" | "groove" | "inset" | "none" | "outset" | "ridge",
        "data-border-top-width"?: "thin" | "thick" | "thinner" | "thicker" | "thinnest" | "thickest",
        "data-border-top-color"?: "accent",
        "data-border-bottom-style"?: "solid" | "dashed" | "dotted" | "double" | "groove" | "inset" | "none" | "outset" | "ridge",
        "data-border-bottom-width"?: "thin" | "thick" | "thinner" | "thicker" | "thinnest" | "thickest",
        "data-border-bottom-color"?: "accent",
        "data-border-top-left-radius"?: "full",
        "data-border-bottom-left-radius"?: "full",
        "data-border-top-right-radius"?: "full",
        "data-border-bottom-right-radius"?: "full",
        "data-color"?: "red" | "blue" | "green" | "lightgreen" | "lightyellow" | "gold" | "goldenrod" | "fuchsia" | "black" | "white" | "accent",
        "data-display"?: "flex" | "grid" | "inline-grid" | "inline-flex" | "vertical-flex",
        "data-fade"?: "bottom",
        "data-flex"?: "stretch-full" | "stretch-half" | "stretch-quarter" | "stretch-three-fourth",
        "data-font-size"?: "small" | "medium" | "large",
        "data-font-style"?: "italic" | "normal" | "oblique",
        "data-font-weight"?: "bold" | "normal" | "bolder" | "lighter",
        "data-justify-items"?: "start" | "self-start" | "end" | "self-end" | "center" | "stretch" | "normal" | "baseline",
        "data-layout"?: "row" | "command-row" | "warning" | "grid2x2" | "grid3x3" | "flex-wrap" | "flex" | "flex-center",
        "data-padding"?: "auto" | "medium" | "large",
        "data-padding-left"?: "auto" | "medium" | "large",
        "data-padding-right"?: "auto" | "medium" | "large",
        "data-padding-top"?: "auto" | "medium" | "large",
        "data-padding-bottom"?: "auto" | "medium" | "large",
        "data-margin"?: "auto" | "medium" | "large",
        "data-margin-left"?: "auto" | "medium" | "large",
        "data-margin-right"?: "auto" | "medium" | "large",
        "data-margin-top"?: "auto" | "medium" | "large",
        "data-margin-bottom"?: "auto" | "medium" | "large",
        "data-text-align"?: "left" | "right" | "center" | "justify",
        "data-text-decoration"?: "underline" | "overline" | "strike-through" | "line-through" | "wavy",
        "data-text-overflow"?: "ellipsis",
        "data-wrap"?: "none",
    }
}
