import styled from "../styled";

styled.add({
    "data-grid-row": {
        "1": styled.css `grid-row: 1;`,
        "2": styled.css `grid-row: 2;`,
        "3": styled.css `grid-row: 3;`,
        "4": styled.css `grid-row: 4;`,
        "5": styled.css `grid-row: 5;`,
        "1 / span 2": styled.css `grid-row: 1 / span 2;`,
        "2 / span 2": styled.css `grid-row: 2 / span 2;`,
        "3 / span 2": styled.css `grid-row: 3 / span 2;`,
        "4 / span 2": styled.css `grid-row: 4 / span 2;`,
        "5 / span 2": styled.css `grid-row: 5 / span 2;`,
        "1 / span 3": styled.css `grid-row: 1 / span 3;`,
        "2 / span 3": styled.css `grid-row: 2 / span 3;`,
        "3 / span 3": styled.css `grid-row: 3 / span 3;`,
        "4 / span 3": styled.css `grid-row: 4 / span 3;`,
        "5 / span 3": styled.css `grid-row: 5 / span 3;`,
        "1 / span 4": styled.css `grid-row: 1 / span 4;`,
        "2 / span 4": styled.css `grid-row: 2 / span 4;`,
        "3 / span 4": styled.css `grid-row: 3 / span 4;`,
        "4 / span 4": styled.css `grid-row: 4 / span 4;`,
        "5 / span 4": styled.css `grid-row: 5 / span 4;`,
        "1 / span 5": styled.css `grid-row: 1 / span 5;`,
        "2 / span 5": styled.css `grid-row: 2 / span 5;`,
        "3 / span 5": styled.css `grid-row: 3 / span 5;`,
        "4 / span 5": styled.css `grid-row: 4 / span 5;`,
        "5 / span 5": styled.css `grid-row: 5 / span 5;`,

    },
    "data-grid-column": {
        "1": styled.css `grid-column: 1;`,
        "2": styled.css `grid-column: 2;`,
        "3": styled.css `grid-column: 3;`,
        "4": styled.css `grid-column: 4;`,
        "5": styled.css `grid-column: 5;`,
        "1 / span 2": styled.css `grid-column: 1 / span 2;`,
        "2 / span 2": styled.css `grid-column: 2 / span 2;`,
        "3 / span 2": styled.css `grid-column: 3 / span 2;`,
        "4 / span 2": styled.css `grid-column: 4 / span 2;`,
        "5 / span 2": styled.css `grid-column: 5 / span 2;`,
        "1 / span 3": styled.css `grid-column: 1 / span 3;`,
        "2 / span 3": styled.css `grid-column: 2 / span 3;`,
        "3 / span 3": styled.css `grid-column: 3 / span 3;`,
        "4 / span 3": styled.css `grid-column: 4 / span 3;`,
        "5 / span 3": styled.css `grid-column: 5 / span 3;`,
        "1 / span 4": styled.css `grid-column: 1 / span 4;`,
        "2 / span 4": styled.css `grid-column: 2 / span 4;`,
        "3 / span 4": styled.css `grid-column: 3 / span 4;`,
        "4 / span 4": styled.css `grid-column: 4 / span 4;`,
        "5 / span 4": styled.css `grid-column: 5 / span 4;`,
        "1 / span 5": styled.css `grid-column: 1 / span 5;`,
        "2 / span 5": styled.css `grid-column: 2 / span 5;`,
        "3 / span 5": styled.css `grid-column: 3 / span 5;`,
        "4 / span 5": styled.css `grid-column: 4 / span 5;`,
        "5 / span 5": styled.css `grid-column: 5 / span 5;`,
    },
    "data-grid-row-span": {
        "2": styled.css `grid-row-end: 2;`,
        "3": styled.css `grid-row-end: 3;`,
        "4": styled.css `grid-row-end: 4;`,
    },
    "data-grid-column-span": {
        "2": styled.css `grid-column-end: 2;`,
        "3": styled.css `grid-column-end: 3;`,
        "4": styled.css `grid-column-end: 4;`,
    },
}, "high");